/*
 * Camunda REST API
 * Swagger OpenApi Spec for Camunda REST API.
 *
 * OpenAPI spec version: v7.8.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.moex.mpfin.qa.utils.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ProcessInstanceQueryDto
 */
public class ProcessInstanceQueryDto {
  @JsonProperty("deploymentId")
  private String deploymentId = null;

  @JsonProperty("processDefinitionKey")
  private String processDefinitionKey = null;

  @JsonProperty("businessKey")
  private String businessKey = null;

  @JsonProperty("businessKeyLike")
  private String businessKeyLike = null;

  @JsonProperty("caseInstanceId")
  private String caseInstanceId = null;

  @JsonProperty("processDefinitionId")
  private String processDefinitionId = null;

  @JsonProperty("superProcessInstance")
  private String superProcessInstance = null;

  @JsonProperty("subProcessInstance")
  private String subProcessInstance = null;

  @JsonProperty("superCaseInstance")
  private String superCaseInstance = null;

  @JsonProperty("subCaseInstance")
  private String subCaseInstance = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("suspended")
  private Boolean suspended = null;

  @JsonProperty("processInstanceIds")
  private List<String> processInstanceIds = null;

  @JsonProperty("incidentId")
  private String incidentId = null;

  @JsonProperty("incidentType")
  private String incidentType = null;

  @JsonProperty("incidentMessage")
  private String incidentMessage = null;

  @JsonProperty("incidentMessageLike")
  private String incidentMessageLike = null;

  @JsonProperty("withoutTenantId")
  private Boolean withoutTenantId = null;

  @JsonProperty("activityIds")
  private List<String> activityIds = null;

  @JsonProperty("variables")
  private List<VariableQueryParameterDto> variables = null;

  @JsonProperty("tenantIdIn")
  private List<String> tenantIdIn = null;

  @JsonProperty("sorting")
  private List<SortingDto> sorting = null;

  public ProcessInstanceQueryDto deploymentId(String deploymentId) {
    this.deploymentId = deploymentId;
    return this;
  }

  /**
   * Filter by the deployment the id belongs to.
   *
   * @return deploymentId
   **/
  public String getDeploymentId() {
    return deploymentId;
  }

  public void setDeploymentId(String deploymentId) {
    this.deploymentId = deploymentId;
  }

  public ProcessInstanceQueryDto processDefinitionKey(String processDefinitionKey) {
    this.processDefinitionKey = processDefinitionKey;
    return this;
  }

  /**
   * Filter by the key of the process definition the instances run on.
   *
   * @return processDefinitionKey
   **/
  public String getProcessDefinitionKey() {
    return processDefinitionKey;
  }

  public void setProcessDefinitionKey(String processDefinitionKey) {
    this.processDefinitionKey = processDefinitionKey;
  }

  public ProcessInstanceQueryDto businessKey(String businessKey) {
    this.businessKey = businessKey;
    return this;
  }

  /**
   * Filter by process instance business key.
   *
   * @return businessKey
   **/
  public String getBusinessKey() {
    return businessKey;
  }

  public void setBusinessKey(String businessKey) {
    this.businessKey = businessKey;
  }

  public ProcessInstanceQueryDto businessKeyLike(String businessKeyLike) {
    this.businessKeyLike = businessKeyLike;
    return this;
  }

  /**
   * Filter by process instance business key that the parameter is a substring of.
   *
   * @return businessKeyLike
   **/
  public String getBusinessKeyLike() {
    return businessKeyLike;
  }

  public void setBusinessKeyLike(String businessKeyLike) {
    this.businessKeyLike = businessKeyLike;
  }

  public ProcessInstanceQueryDto caseInstanceId(String caseInstanceId) {
    this.caseInstanceId = caseInstanceId;
    return this;
  }

  /**
   * Filter by case instance id.
   *
   * @return caseInstanceId
   **/
  public String getCaseInstanceId() {
    return caseInstanceId;
  }

  public void setCaseInstanceId(String caseInstanceId) {
    this.caseInstanceId = caseInstanceId;
  }

  public ProcessInstanceQueryDto processDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
    return this;
  }

  /**
   * Filter by the process definition the instances run on.
   *
   * @return processDefinitionId
   **/
  public String getProcessDefinitionId() {
    return processDefinitionId;
  }

  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }

  public ProcessInstanceQueryDto superProcessInstance(String superProcessInstance) {
    this.superProcessInstance = superProcessInstance;
    return this;
  }

  /**
   * Restrict query to all process instances that are sub process instances of the given process instance. Takes a process instance id.
   *
   * @return superProcessInstance
   **/
  public String getSuperProcessInstance() {
    return superProcessInstance;
  }

  public void setSuperProcessInstance(String superProcessInstance) {
    this.superProcessInstance = superProcessInstance;
  }

  public ProcessInstanceQueryDto subProcessInstance(String subProcessInstance) {
    this.subProcessInstance = subProcessInstance;
    return this;
  }

  /**
   * Restrict query to all process instances that have the given process instance as a sub process instance. Takes a process instance id.
   *
   * @return subProcessInstance
   **/
  public String getSubProcessInstance() {
    return subProcessInstance;
  }

  public void setSubProcessInstance(String subProcessInstance) {
    this.subProcessInstance = subProcessInstance;
  }

  public ProcessInstanceQueryDto superCaseInstance(String superCaseInstance) {
    this.superCaseInstance = superCaseInstance;
    return this;
  }

  /**
   * Restrict query to all process instances that are sub process instances of the given case instance. Takes a case instance id.
   *
   * @return superCaseInstance
   **/
  public String getSuperCaseInstance() {
    return superCaseInstance;
  }

  public void setSuperCaseInstance(String superCaseInstance) {
    this.superCaseInstance = superCaseInstance;
  }

  public ProcessInstanceQueryDto subCaseInstance(String subCaseInstance) {
    this.subCaseInstance = subCaseInstance;
    return this;
  }

  /**
   * Restrict query to all process instances that have the given case instance as a sub case instance. Takes a case instance id.
   *
   * @return subCaseInstance
   **/
  public String getSubCaseInstance() {
    return subCaseInstance;
  }

  public void setSubCaseInstance(String subCaseInstance) {
    this.subCaseInstance = subCaseInstance;
  }

  public ProcessInstanceQueryDto active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   *
   * @return active
   **/

  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public ProcessInstanceQueryDto suspended(Boolean suspended) {
    this.suspended = suspended;
    return this;
  }

  /**
   * Get suspended
   *
   * @return suspended
   **/

  public Boolean isSuspended() {
    return suspended;
  }

  public void setSuspended(Boolean suspended) {
    this.suspended = suspended;
  }

  public ProcessInstanceQueryDto processInstanceIds(List<String> processInstanceIds) {
    this.processInstanceIds = processInstanceIds;
    return this;
  }

  public ProcessInstanceQueryDto addProcessInstanceIdsItem(String processInstanceIdsItem) {
    if (this.processInstanceIds == null) {
      this.processInstanceIds = new ArrayList<>();
    }
    this.processInstanceIds.add(processInstanceIdsItem);
    return this;
  }

  /**
   * Filter by a list of process instance ids. Must be a JSON array of Strings.
   *
   * @return processInstanceIds
   **/

  public List<String> getProcessInstanceIds() {
    return processInstanceIds;
  }

  public void setProcessInstanceIds(List<String> processInstanceIds) {
    this.processInstanceIds = processInstanceIds;
  }

  public ProcessInstanceQueryDto incidentId(String incidentId) {
    this.incidentId = incidentId;
    return this;
  }

  /**
   * Filter by the incident id.
   *
   * @return incidentId
   **/

  public String getIncidentId() {
    return incidentId;
  }

  public void setIncidentId(String incidentId) {
    this.incidentId = incidentId;
  }

  public ProcessInstanceQueryDto incidentType(String incidentType) {
    this.incidentType = incidentType;
    return this;
  }

  /**
   * Filter by the incident type. See the User Guide for a list of incident types.
   *
   * @return incidentType
   **/

  public String getIncidentType() {
    return incidentType;
  }

  public void setIncidentType(String incidentType) {
    this.incidentType = incidentType;
  }

  public ProcessInstanceQueryDto incidentMessage(String incidentMessage) {
    this.incidentMessage = incidentMessage;
    return this;
  }

  /**
   * Filter by the incident message. Exact match.
   *
   * @return incidentMessage
   **/

  public String getIncidentMessage() {
    return incidentMessage;
  }

  public void setIncidentMessage(String incidentMessage) {
    this.incidentMessage = incidentMessage;
  }

  public ProcessInstanceQueryDto incidentMessageLike(String incidentMessageLike) {
    this.incidentMessageLike = incidentMessageLike;
    return this;
  }

  /**
   * Filter by the incident message that the parameter is a substring of.
   *
   * @return incidentMessageLike
   **/

  public String getIncidentMessageLike() {
    return incidentMessageLike;
  }

  public void setIncidentMessageLike(String incidentMessageLike) {
    this.incidentMessageLike = incidentMessageLike;
  }

  public ProcessInstanceQueryDto withoutTenantId(Boolean withoutTenantId) {
    this.withoutTenantId = withoutTenantId;
    return this;
  }

  /**
   * Get withoutTenantId
   *
   * @return withoutTenantId
   **/

  public Boolean isWithoutTenantId() {
    return withoutTenantId;
  }

  public void setWithoutTenantId(Boolean withoutTenantId) {
    this.withoutTenantId = withoutTenantId;
  }

  public ProcessInstanceQueryDto activityIds(List<String> activityIds) {
    this.activityIds = activityIds;
    return this;
  }

  public ProcessInstanceQueryDto addActivityIdsItem(String activityIdsItem) {
    if (this.activityIds == null) {
      this.activityIds = new ArrayList<>();
    }
    this.activityIds.add(activityIdsItem);
    return this;
  }

  /**
   * Get activityIds
   *
   * @return activityIds
   **/

  public List<String> getActivityIds() {
    return activityIds;
  }

  public void setActivityIds(List<String> activityIds) {
    this.activityIds = activityIds;
  }

  public ProcessInstanceQueryDto variables(List<VariableQueryParameterDto> variables) {
    this.variables = variables;
    return this;
  }

  public ProcessInstanceQueryDto addVariablesItem(VariableQueryParameterDto variablesItem) {
    if (this.variables == null) {
      this.variables = new ArrayList<>();
    }
    this.variables.add(variablesItem);
    return this;
  }

  /**
   * A JSON array to only include process instances that have variables with certain values. The array consists of objects with the three properties key, operator and value. key (String) is the variable name, operator (String) is the comparison operator to be used and value the variable value. value may be String, Number or Boolean. Valid operator values are: eq - equal to; neq - not equal to; gt - greater than; gteq - greater than or equal to; lt - lower than; lteq - lower than or equal to; like.
   *
   * @return variables
   **/

  public List<VariableQueryParameterDto> getVariables() {
    return variables;
  }

  public void setVariables(List<VariableQueryParameterDto> variables) {
    this.variables = variables;
  }

  public ProcessInstanceQueryDto tenantIdIn(List<String> tenantIdIn) {
    this.tenantIdIn = tenantIdIn;
    return this;
  }

  public ProcessInstanceQueryDto addTenantIdInItem(String tenantIdInItem) {
    if (this.tenantIdIn == null) {
      this.tenantIdIn = new ArrayList<>();
    }
    this.tenantIdIn.add(tenantIdInItem);
    return this;
  }

  /**
   * Filter by a list of tenant ids. A process instance must have one of the given tenant ids. Must be a JSON array of Strings.
   *
   * @return tenantIdIn
   **/

  public List<String> getTenantIdIn() {
    return tenantIdIn;
  }

  public void setTenantIdIn(List<String> tenantIdIn) {
    this.tenantIdIn = tenantIdIn;
  }

  public ProcessInstanceQueryDto sorting(List<SortingDto> sorting) {
    this.sorting = sorting;
    return this;
  }

  public ProcessInstanceQueryDto addSortingItem(SortingDto sortingItem) {
    if (this.sorting == null) {
      this.sorting = new ArrayList<>();
    }
    this.sorting.add(sortingItem);
    return this;
  }

  /**
   * Get sorting
   *
   * @return sorting
   **/

  public List<SortingDto> getSorting() {
    return sorting;
  }

  public void setSorting(List<SortingDto> sorting) {
    this.sorting = sorting;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessInstanceQueryDto processInstanceQueryDto = (ProcessInstanceQueryDto) o;
    return Objects.equals(this.deploymentId, processInstanceQueryDto.deploymentId) &&
        Objects.equals(this.processDefinitionKey, processInstanceQueryDto.processDefinitionKey) &&
        Objects.equals(this.businessKey, processInstanceQueryDto.businessKey) &&
        Objects.equals(this.businessKeyLike, processInstanceQueryDto.businessKeyLike) &&
        Objects.equals(this.caseInstanceId, processInstanceQueryDto.caseInstanceId) &&
        Objects.equals(this.processDefinitionId, processInstanceQueryDto.processDefinitionId) &&
        Objects.equals(this.superProcessInstance, processInstanceQueryDto.superProcessInstance) &&
        Objects.equals(this.subProcessInstance, processInstanceQueryDto.subProcessInstance) &&
        Objects.equals(this.superCaseInstance, processInstanceQueryDto.superCaseInstance) &&
        Objects.equals(this.subCaseInstance, processInstanceQueryDto.subCaseInstance) &&
        Objects.equals(this.active, processInstanceQueryDto.active) &&
        Objects.equals(this.suspended, processInstanceQueryDto.suspended) &&
        Objects.equals(this.processInstanceIds, processInstanceQueryDto.processInstanceIds) &&
        Objects.equals(this.incidentId, processInstanceQueryDto.incidentId) &&
        Objects.equals(this.incidentType, processInstanceQueryDto.incidentType) &&
        Objects.equals(this.incidentMessage, processInstanceQueryDto.incidentMessage) &&
        Objects.equals(this.incidentMessageLike, processInstanceQueryDto.incidentMessageLike) &&
        Objects.equals(this.withoutTenantId, processInstanceQueryDto.withoutTenantId) &&
        Objects.equals(this.activityIds, processInstanceQueryDto.activityIds) &&
        Objects.equals(this.variables, processInstanceQueryDto.variables) &&
        Objects.equals(this.tenantIdIn, processInstanceQueryDto.tenantIdIn) &&
        Objects.equals(this.sorting, processInstanceQueryDto.sorting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deploymentId, processDefinitionKey, businessKey, businessKeyLike, caseInstanceId, processDefinitionId, superProcessInstance, subProcessInstance, superCaseInstance, subCaseInstance, active, suspended, processInstanceIds, incidentId, incidentType, incidentMessage, incidentMessageLike, withoutTenantId, activityIds, variables, tenantIdIn, sorting);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessInstanceQueryDto {\n");

    sb.append("    deploymentId: ").append(toIndentedString(deploymentId)).append("\n");
    sb.append("    processDefinitionKey: ").append(toIndentedString(processDefinitionKey)).append("\n");
    sb.append("    businessKey: ").append(toIndentedString(businessKey)).append("\n");
    sb.append("    businessKeyLike: ").append(toIndentedString(businessKeyLike)).append("\n");
    sb.append("    caseInstanceId: ").append(toIndentedString(caseInstanceId)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    superProcessInstance: ").append(toIndentedString(superProcessInstance)).append("\n");
    sb.append("    subProcessInstance: ").append(toIndentedString(subProcessInstance)).append("\n");
    sb.append("    superCaseInstance: ").append(toIndentedString(superCaseInstance)).append("\n");
    sb.append("    subCaseInstance: ").append(toIndentedString(subCaseInstance)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    suspended: ").append(toIndentedString(suspended)).append("\n");
    sb.append("    processInstanceIds: ").append(toIndentedString(processInstanceIds)).append("\n");
    sb.append("    incidentId: ").append(toIndentedString(incidentId)).append("\n");
    sb.append("    incidentType: ").append(toIndentedString(incidentType)).append("\n");
    sb.append("    incidentMessage: ").append(toIndentedString(incidentMessage)).append("\n");
    sb.append("    incidentMessageLike: ").append(toIndentedString(incidentMessageLike)).append("\n");
    sb.append("    withoutTenantId: ").append(toIndentedString(withoutTenantId)).append("\n");
    sb.append("    activityIds: ").append(toIndentedString(activityIds)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    tenantIdIn: ").append(toIndentedString(tenantIdIn)).append("\n");
    sb.append("    sorting: ").append(toIndentedString(sorting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

