/*
 * Camunda REST API
 * Swagger OpenApi Spec for Camunda REST API.
 *
 * OpenAPI spec version: v7.8.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.moex.mpfin.qa.utils.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * ProcessInstanceModificationInstructionDto
 */
@JsonSubTypes({
    @JsonSubTypes.Type(value = StartBeforeInstructionDto.class, name = "StartBeforeInstructionDto"),
    @JsonSubTypes.Type(value = StartTransitionInstructionDto.class, name = "StartTransitionInstructionDto"),
    @JsonSubTypes.Type(value = CancellationInstructionDto.class, name = "CancellationInstructionDto"),
    @JsonSubTypes.Type(value = StartAfterInstructionDto.class, name = "StartAfterInstructionDto"),
})

public class ProcessInstanceModificationInstructionDto {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("variables")
  private Map<String, TriggerVariableValueDto> variables = null;

  @JsonProperty("activityId")
  private String activityId = null;

  @JsonProperty("transitionId")
  private String transitionId = null;

  @JsonProperty("activityInstanceId")
  private String activityInstanceId = null;

  @JsonProperty("transitionInstanceId")
  private String transitionInstanceId = null;

  @JsonProperty("ancestorActivityInstanceId")
  private String ancestorActivityInstanceId = null;

  @JsonProperty("cancelCurrentActiveActivityInstances")
  private Boolean cancelCurrentActiveActivityInstances = null;

  public ProcessInstanceModificationInstructionDto type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ProcessInstanceModificationInstructionDto variables(Map<String, TriggerVariableValueDto> variables) {
    this.variables = variables;
    return this;
  }

  public ProcessInstanceModificationInstructionDto putVariablesItem(String key, TriggerVariableValueDto variablesItem) {
    if (this.variables == null) {
      this.variables = new HashMap<>();
    }
    this.variables.put(key, variablesItem);
    return this;
  }

  /**
   * Get variables
   *
   * @return variables
   **/
  public Map<String, TriggerVariableValueDto> getVariables() {
    return variables;
  }

  public void setVariables(Map<String, TriggerVariableValueDto> variables) {
    this.variables = variables;
  }

  public ProcessInstanceModificationInstructionDto activityId(String activityId) {
    this.activityId = activityId;
    return this;
  }

  /**
   * Get activityId
   *
   * @return activityId
   **/
  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public ProcessInstanceModificationInstructionDto transitionId(String transitionId) {
    this.transitionId = transitionId;
    return this;
  }

  /**
   * Get transitionId
   *
   * @return transitionId
   **/
  public String getTransitionId() {
    return transitionId;
  }

  public void setTransitionId(String transitionId) {
    this.transitionId = transitionId;
  }

  public ProcessInstanceModificationInstructionDto activityInstanceId(String activityInstanceId) {
    this.activityInstanceId = activityInstanceId;
    return this;
  }

  /**
   * Get activityInstanceId
   *
   * @return activityInstanceId
   **/
  public String getActivityInstanceId() {
    return activityInstanceId;
  }

  public void setActivityInstanceId(String activityInstanceId) {
    this.activityInstanceId = activityInstanceId;
  }

  public ProcessInstanceModificationInstructionDto transitionInstanceId(String transitionInstanceId) {
    this.transitionInstanceId = transitionInstanceId;
    return this;
  }

  /**
   * Get transitionInstanceId
   *
   * @return transitionInstanceId
   **/
  public String getTransitionInstanceId() {
    return transitionInstanceId;
  }

  public void setTransitionInstanceId(String transitionInstanceId) {
    this.transitionInstanceId = transitionInstanceId;
  }

  public ProcessInstanceModificationInstructionDto ancestorActivityInstanceId(String ancestorActivityInstanceId) {
    this.ancestorActivityInstanceId = ancestorActivityInstanceId;
    return this;
  }

  /**
   * Get ancestorActivityInstanceId
   *
   * @return ancestorActivityInstanceId
   **/
  public String getAncestorActivityInstanceId() {
    return ancestorActivityInstanceId;
  }

  public void setAncestorActivityInstanceId(String ancestorActivityInstanceId) {
    this.ancestorActivityInstanceId = ancestorActivityInstanceId;
  }

  public ProcessInstanceModificationInstructionDto cancelCurrentActiveActivityInstances(Boolean cancelCurrentActiveActivityInstances) {
    this.cancelCurrentActiveActivityInstances = cancelCurrentActiveActivityInstances;
    return this;
  }

  /**
   * Get cancelCurrentActiveActivityInstances
   *
   * @return cancelCurrentActiveActivityInstances
   **/
  public Boolean isCancelCurrentActiveActivityInstances() {
    return cancelCurrentActiveActivityInstances;
  }

  public void setCancelCurrentActiveActivityInstances(Boolean cancelCurrentActiveActivityInstances) {
    this.cancelCurrentActiveActivityInstances = cancelCurrentActiveActivityInstances;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessInstanceModificationInstructionDto processInstanceModificationInstructionDto = (ProcessInstanceModificationInstructionDto) o;
    return Objects.equals(this.type, processInstanceModificationInstructionDto.type) &&
        Objects.equals(this.variables, processInstanceModificationInstructionDto.variables) &&
        Objects.equals(this.activityId, processInstanceModificationInstructionDto.activityId) &&
        Objects.equals(this.transitionId, processInstanceModificationInstructionDto.transitionId) &&
        Objects.equals(this.activityInstanceId, processInstanceModificationInstructionDto.activityInstanceId) &&
        Objects.equals(this.transitionInstanceId, processInstanceModificationInstructionDto.transitionInstanceId) &&
        Objects.equals(this.ancestorActivityInstanceId, processInstanceModificationInstructionDto.ancestorActivityInstanceId) &&
        Objects.equals(this.cancelCurrentActiveActivityInstances, processInstanceModificationInstructionDto.cancelCurrentActiveActivityInstances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, variables, activityId, transitionId, activityInstanceId, transitionInstanceId, ancestorActivityInstanceId, cancelCurrentActiveActivityInstances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessInstanceModificationInstructionDto {\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    transitionId: ").append(toIndentedString(transitionId)).append("\n");
    sb.append("    activityInstanceId: ").append(toIndentedString(activityInstanceId)).append("\n");
    sb.append("    transitionInstanceId: ").append(toIndentedString(transitionInstanceId)).append("\n");
    sb.append("    ancestorActivityInstanceId: ").append(toIndentedString(ancestorActivityInstanceId)).append("\n");
    sb.append("    cancelCurrentActiveActivityInstances: ").append(toIndentedString(cancelCurrentActiveActivityInstances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

