/*
 * Camunda REST API
 * Swagger OpenApi Spec for Camunda REST API.
 *
 * OpenAPI spec version: v7.8.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.moex.mpfin.qa.utils.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/**
 * VariableQueryParameterDto
 */
public class VariableQueryParameterDto {
  @JsonProperty("operator")
  private String operator = null;

  @JsonProperty("value")
  private Object value = null;

  @JsonProperty("name")
  private String name = null;

  public VariableQueryParameterDto operator(String operator) {
    this.operator = operator;
    return this;
  }

  /**
   * Get operator
   *
   * @return operator
   **/

  public String getOperator() {
    return operator;
  }

  public void setOperator(String operator) {
    this.operator = operator;
  }

  public VariableQueryParameterDto value(Object value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   *
   * @return value
   **/

  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }

  public VariableQueryParameterDto name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableQueryParameterDto variableQueryParameterDto = (VariableQueryParameterDto) o;
    return Objects.equals(this.operator, variableQueryParameterDto.operator) &&
        Objects.equals(this.value, variableQueryParameterDto.value) &&
        Objects.equals(this.name, variableQueryParameterDto.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operator, value, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableQueryParameterDto {\n");

    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

